[package]
name = "rainbow-wrapper"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
half = "2.5.0"
indexmap = "2.8.0"
fox = { git="https://github.com/stormyhs/fox.git" }
